artifact_root: artifacts



data_ingestion:
    root_dir: artifacts/data_ingestion
    source_URL:https://github.com/niz121/End-to-end-Wine-quality/raw/refs/heads/main/winequality-data.zip
    local_data_file: artifacts/data_ingestion/data/winequality-data.zip
    unzip_dir: artifacts/data_ingestion